"""fix centro_treinamento_id typo

Revision ID: 45936a48fc83
Revises: cb7f21dc6f04
Create Date: 2025-08-29 14:28:12.770145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45936a48fc83'
down_revision: Union[str, None] = 'cb7f21dc6f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centro_treinamento_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('atletas_entro_treinamento_id_fkey'), 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'entro_treinamento_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('entro_treinamento_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key(op.f('atletas_entro_treinamento_id_fkey'), 'atletas', 'centros_treinamento', ['entro_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'centro_treinamento_id')
    # ### end Alembic commands ###
